### ISSUE TITLE
ERROR:  type "earth" does not exist at character 136

### ISSUE THREAD

**Issue by ncri** [diogob/activerecord-postgres-earthdistance#30] opened 2017-04-14 06:05 UTC
Everything seems to wok fine, but checking our rails app's logs we keep seeing this:

```
[DATABASE] [4-1] ERROR:  type "earth" does not exist at character 136 
[DATABASE] [4-2] QUERY:  SELECT cube(cube(cube(earth()*cos(radians($1))*cos(radians($2))),earth()*cos(radians($1))*sin(radians($2))),earth()*sin(radians($1)))::earth 
[DATABASE] [4-3] CONTEXT:  SQL function "ll_to_earth" during inlining 
[DATABASE] [4-4] 	automatic analyze of table "d2la77ueqce997.public.addresses" 
```

We use postgresql 9.6.1

**Comment by diogob** [comment] 2017-04-14 22:05
Hi there, if the queries are working fine in the app, that line might indicate that in some database session the `ll_to_earth` function is called without having access to the schema where the extension was installed. The type earth should have been installed with the earthdistance extension (probably in your `public` schema).

If you connect using the `psql` and issue the command `\dT` you should see something similar to:
```
                                              List of data types
 Schema | Name  |                                         Description
--------+-------+---------------------------------------------------------------------------------------------
 public | cube  | multi-dimensional cube '(FLOAT-1, FLOAT-2, ..., FLOAT-N), (FLOAT-1, FLOAT-2, ..., FLOAT-N)'
 public | earth |
(2 rows)
```

**Comment by ncri** [comment] 2017-04-15 05:33
Yes, I see exactly this:

```
\dT
                                              List of data types
 Schema | Name  |                                         Description                                         
--------+-------+---------------------------------------------------------------------------------------------
 public | cube  | multi-dimensional cube '(FLOAT-1, FLOAT-2, ..., FLOAT-N), (FLOAT-1, FLOAT-2, ..., FLOAT-N)'
 public | earth | 

```

But still having the error. Odd. The DB is on Heroku, maybe they somehow limit access.
Maybe i need to contact them.

Wondering if the error here https://github.com/2ndQuadrant/bdr/issues/252 is the same. Seems they solve it by prefixing the function calls with `public.`. But I cannot even redefine functions on the Heroku as they limit access. I can only add and remove whitelisted extensions I think.

**Comment by diogob** [comment] 2017-04-15 18:32
Yes, it seems to be related. And someone even filled a bug in PostgreSQL (#14372). 
This explanation seems to fit your case: https://github.com/2ndQuadrant/bdr/issues/252#issuecomment-253718950

You probably can work around using an appropriate `SET search_path` command before executing whatever is causing that error.

I'm closing this issue since it seems out of reach for this gem's code to solve. Feel free to reopen if you find new information.

**Closed by diogob** 2017-04-15 18:32 UTC

**Comment by ncri** [comment] 2017-04-16 07:42
Okay. I wonder if i could just try to remove the extension and then add it by running the earthdistance.sql file from your gem, modified, prefixing `earth()` with `public.`. Will try that but seems hackish and I might alos not have the permission for that on Heroku.

**Comment by ded** [comment] 2017-07-04 01:46
@ncri sorry to bother months later. did you end up solving your issue independently? I'm seeing the exact same error message (even the same line number at `character 136`). furthermore i'm on the same version of Postgres... so I could definitely use a point in the right direction.

**Comment by ncri** [comment] 2017-07-04 06:52
I was setting up a new db, that solved it.

**Comment by GAKINDUSTRIES** [comment] 2018-03-10 17:53
Hey, @ncri  @ded I'm working with Heroku database, I tried by resetting the database `heroku pg:reset DATABASE_URL` and run migrations again, and then import all data from CSV, but the issue is still there. How do you @ncri figure it out? Thanks, and sorry to bother you long after.

**Comment by ncri** [comment] 2018-03-10 20:35
I needed to setup a complete new db on Heroku to solve it.

**Comment by GAKINDUSTRIES** [comment] 2018-03-12 16:41
@ncri Thanks for your quick response. It seems to be solved for me as well. I tried by resetting the database again and upload a dump from the same database that I created a few days ago. The logs have disappeared. Pretty weird though. Hope it helps to somebody. Thanks.

**Comment by darrenterhune** [comment] 2018-06-20 18:36
Little different situation but same error. This is one of the only rails related searches you'll find on the problem in google so hoping this helps someone out. 

This happened on an app I am working on. We traced it to `postgres` upgrading to `9.6.9` from `9.6.2` where `pg_dumb` adds this new line in your structure.sql file after upgrading:

```
SELECT pg_catalog.set_config('search_path', '', false);
```

The extension seems to be using the `search_path` but expects the extension to be in the public schema. If you set that line to `SELECT pg_catalog.set_config('search_path', 'public', false);` the errors go away. However every time you run a `db:migrate` it's going to add it back. We simply downgraded `postgres` for now unless we can migrate to 10.

**Comment by teachernah** [comment] 2018-07-15 05:06
create table Customer (
  custID int primary key not null,
  Name nvarchar(50) not null,
  address nvarchar(50) not null,
  email nvarchar(50) not null
);

create table CATEGORY (
  catID int primary key not null,
  catName nvarchar(50) not null,
  intialRate float(50) not null
);

create table SERVICES (
  serID int primary key not null,
  serTitle nvarchar(50) not null,
  serDescription nvarchar(max) not null,
  serCharges float(50)
);

create table FOOD-ITEM (
  itemID int primary key not null,
  itemName nvarchar(50) not null,
  description nvarchar(max) not null
)+;


create table MENU (
  menuId int primary key not null,
  noOfserving int not null,
  Quantity int not null,
  noOfItems int not null
);

create table VENUE (
  location nvarchar(250) not null,
  city nvarchar(250) not null,
  capacity nvarchar(250) not null,
  description nvarchar(250) not null
);

create table EVENT (
  eId int primary key not null,
  Date date not null,
  timeSlot time not null
);

This is my table. Please tell me what is the problem in it

**Comment by hishammalik** [comment] 2018-09-08 13:40
I ended up coming to this thread with no clear answer, and finally found the solution deep in between the discussion. Posting here for everyone who gets stuck. The solution is to redefine ll_to_earth method from postgres console like this:
```
CREATE OR REPLACE FUNCTION ll_to_earth(
    double precision,
    double precision)
  RETURNS earth AS
'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians($1))*cos(radians($2))),public.earth()*cos(radians($1))*sin(radians($2))),public.earth()*sin(radians($1)))::public.earth'
  LANGUAGE sql IMMUTABLE STRICT
  COST 100;
```

**Comment by nemtsov** [comment] 2018-09-23 05:35
In case it helps, I'm also seeing this on postgres >= 10.3. 10.2 doesn't have the issue (tested with the official docker images 10.2 up to 10.5).

**Comment by darkuranium** [comment] 2020-06-04 07:06
> I ended up coming to this thread with no clear answer, and finally found the solution deep in between the discussion. Posting here for everyone who gets stuck. The solution is to redefine ll_to_earth method from postgres console like this:
> 
> ```
> CREATE OR REPLACE FUNCTION ll_to_earth(
>     double precision,
>     double precision)
>   RETURNS earth AS
> 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians($1))*cos(radians($2))),public.earth()*cos(radians($1))*sin(radians($2))),public.earth()*sin(radians($1)))::public.earth'
>   LANGUAGE sql IMMUTABLE STRICT
>   COST 100;
> ```

I found this issue while looking for a solution to the general problem (i.e. not specific to this software).

The quoted solution *is* what needs to be done, but it wasn't clear to me *what* changed (since the original/unmodified function is not provided).

**So, for those who happen upon this ticket in the same manner as I did, and are looking for a general solution:**
What you need to do is to explicitly prefix anything declared in the database with `public.`, so that it does not depend on the search path. E.g. `earth()`&rarr;`public.earth()`. This also holds for types. The `RETURNS $type` return-type specification does *not* have to be prefixed.

(apologies for hijacking the ticket for this; I hope you won't mind, as it seems to be one of the top results in Google, so it might help many others!)

**Comment by nodesocket** [comment] 2020-10-12 21:06
@hishammalik I am trying your suggested fix as I am running into this problem on AWS RDS trying to upgrade from version `9.5.15` to `9.6.18` and getting `ERROR:  must be owner of function ll_to_earth`:

```
app_staging=> CREATE OR REPLACE FUNCTION ll_to_earth(
app_staging(>     double precision,
app_staging(>     double precision)
app_staging->   RETURNS earth AS
app_staging-> 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians($1))*cos(radians($2))),public.earth()*cos(radians($1))*sin(radians($2))),public.earth()*sin(radians($1)))::public.earth'
app_staging->   LANGUAGE sql IMMUTABLE STRICT
app_staging->   COST 100;

ERROR:  must be owner of function ll_to_earth
```

Any ideas?

**Comment by fpariani** [comment] 2020-12-17 14:41
This is the solution I found so far:

Create an initializer containing the following:

```ruby
module ActiveRecord
  module Tasks
    class CustomPostgreSQLDatabaseTasks < ActiveRecord::Tasks::PostgreSQLDatabaseTasks
      def structure_dump(filename, extra_flags)
        super
        content = File.read(filename)
        earthdistance_extension = 'CREATE EXTENSION IF NOT EXISTS earthdistance WITH SCHEMA public;'
        new_content = content.gsub(
          earthdistance_extension,
          "#{earthdistance_extension}\n\nALTER FUNCTION public.ll_to_earth SET search_path = public;"
        )
        File.open(filename, 'w') { |f| f.puts new_content }
      end
    end
  end
end

module ActiveRecord
  module Tasks
    module DatabaseTasks
      register_task(/postgresql/, 'ActiveRecord::Tasks::CustomPostgreSQLDatabaseTasks')
    end
  end
end
```

**Comment by ace-express** [comment] 2023-07-31 06:37
Just do that to fix the search path of function ll_to_earth
```sql
ALTER FUNCTION ll_to_earth SET search_path = public;
```

**Comment by elapshynov** [comment] 2024-05-21 14:56
Thanks to @ace-express fixed this issue with these steps:
1) Create database where you want to restore
2) Run extension initialization script inside of newly created DB (presented below)
3) Run restore sql dump operation

Extension initialization script:
```psql
CREATE EXTENSION IF NOT EXISTS cube WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS earthdistance WITH SCHEMA public;
ALTER FUNCTION public.ll_to_earth SET search_path = public;
```

**Comment by cgunther** [comment] 2025-04-07 13:56
postgres v17.3 (earthdistance v1.2) may have fixed this.

>Use SQL-standard function bodies in the declarations of contrib/earthdistance's SQL-language functions (Tom Lane, Ronan Dunklau) [§](https://postgr.es/c/3652de36e)
This change allows their references to contrib/cube to be resolved during extension creation, reducing the risk of search-path-based failures and possible attacks.
In particular, this restores their usability in contexts like generated columns, for which PostgreSQL v17 restricts the search path on security grounds. We have received reports of databases failing to be upgraded to v17 because of that. This patch has been included in v16 to provide a workaround: updating the earthdistance extension to this version beforehand should allow an upgrade to succeed.

https://www.postgresql.org/docs/release/17.3/

It's still early but it seems I no longer need the patch to set the search path on the function after that update.

**Comment by skion** [comment] 2026-03-13 20:30
I still needed to set both of these on 18.1:

```postgres
ALTER FUNCTION ll_to_earth SET search_path = public;
ALTER FUNCTION earth_box SET search_path = public;
```
